### ISSUE TITLE
get error deadlock

### ISSUE THREAD

**Issue by aiwantaozi** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#19]
Hi guys,

Just use this plugin, try to get java stack trace from docker json log. And get some error. 

Error from fluentd:

2017-11-07 20:55:17 +0800 [warn]: #0 fluent/log.rb:336:warn: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" tag="myparse.var.lib.docker.containers.19a29c4ffc64257187ac556e8ee88e3977fc0466b267cd5791474e724c089931.19a29c4ffc64257187ac556e8ee88e3977fc0466b267cd5791474e724c089931-json.log"
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:88:in `process_record'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:80:in `block in emit'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event.rb:107:in `each'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:79:in `emit'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/compat/output.rb:164:in `process'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:739:in `emit_sync'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event_router.rb:96:in `emit_stream'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event_router.rb:87:in `emit'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:97:in `block (2 levels) in process_record'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/exception_detector.rb:244:in `flush'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/exception_detector.rb:290:in `update_buffer'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/exception_detector.rb:225:in `push'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:101:in `block in process_record'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:88:in `process_record'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:80:in `block in emit'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event.rb:193:in `block in each'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event.rb:192:in `each'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event.rb:192:in `each'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4/gems/fluent-plugin-detect-exceptions-0.0.8/lib/fluent/plugin/out_detect_exceptions.rb:79:in `emit'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/compat/output.rb:164:in `process'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:739:in `emit_sync'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/event_router.rb:96:in `emit_stream'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:349:in `receive_lines'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:466:in `wrap_receive_lines'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:667:in `block in on_notify'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:708:in `with_io'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:645:in `on_notify'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:497:in `on_notify'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:470:in `attach'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:240:in `setup_watcher'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:297:in `update_watcher'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:555:in `call'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:555:in `on_rotate'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:755:in `on_notify'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin/in_tail.rb:495:in `on_notify'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin_helper/timer.rb:77:in `on_timer'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/cool.io-1.5.1/lib/cool.io/loop.rb:88:in `run_once'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/cool.io-1.5.1/lib/cool.io/loop.rb:88:in `run'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin_helper/event_loop.rb:84:in `block in start'
  2017-11-07 20:55:17 +0800 [warn]: #0 fluent/event_router.rb:87:emit: /Users/fengcaixiao/.rvm/gems/ruby-2.3.4@global/gems/fluentd-0.14.21/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

my Fluentd config:
<source>
  type tail
  path /var/lib/docker/containers/*/*.log
  pos_file /fluentd/etc/fluentd-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag myparse.*
  format json
  read_from_head true
</source>
<match myparse.**>
  @type detect_exceptions
  message log
  languages java
  multiline_flush_interval 1
</match>

my log file:
{"log":"java.lang.Exception: have problem！\r\n","stream":"stdout","time":"2017-11-07T11:28:52.24914817Z"}
{"log":"\u0009at HelloWorld.f(HelloWorld.java:3)\r\n","stream":"stdout","time":"2017-11-07T11:28:52.249895103Z"}
{"log":"\u0009at HelloWorld.g(HelloWorld.java:7)\r\n","stream":"stdout","time":"2017-11-07T11:28:52.249908132Z"}
{"log":"\u0009at HelloWorld.main(HelloWorld.java:16)\r\n","stream":"stdout","time":"2017-11-07T11:28:52.249911345Z"}
{"log":"java.lang.Exception: have problem！\r\n","stream":"stdout","time":"2017-11-07T11:28:52.249913815Z"}
{"log":"\u0009at HelloWorld.f(HelloWorld.java:3)\r\n","stream":"stdout","time":"2017-11-07T11:28:52.250591595Z"}
{"log":"\u0009at HelloWorld.g(HelloWorld.java:7)\r\n","stream":"stdout","time":"2017-11-07T11:28:52.251481109Z"}

**Comment by igorpeshansky** [comment]
@zombiezen FYI. Could be related to #18.

**Comment by igorpeshansky** [comment]
Never mind my previous comment. There are two problems here:
- your config does not specify `remove_tag_prefix`, so the records get routed right back to the `detect_exceptions` plugin, causing an infinite loop.
- this behavior is underdocumented and non-obvious. I know that there exist plugins that allow forwarding the same tag down the chain without an infinite loop, so we can fix this in the `detect_exceptions` code.
So, the workaround for you would be to add a prefix to the tags matched by this plugin and have the plugin strip them off. I'll leave this issue open to fix this properly.

**Comment by aiwantaozi** [comment]
thank you, after adding the remove_tag_prefix, it works.
For what reason this plugin is in match part, not in the filter, parser or formater?

**Comment by igorpeshansky** [comment]
Great, I'm glad it works for you. This is an output plugin because it consumes and generates new log records, rather than transforming existing ones. We'll investigate ways to make it less prone to infinite recursion...

**Comment by aiwantaozi** [comment]
Cool, can't wait to see that.

**Comment by vide** [comment]
Mmmh the fix doesn't work for me. I have this error:

```
2018-02-13 12:06:46 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" tag="kubernetes.var.log.containers.fluentd-es-v2.0.2-jl929_kube-system_fluentd-es-4eb5e468aec589f4a9ca8ce7d1e907cd43311b2aefecf0c02ff5318f9b0f9a6e.log"
```

so I add a`remove_tag_prefix: kubernetes` but then I get

```
2018-02-13 12:06:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" tag="var.log.containers.fluentd-es-v2.0.2-jl929_kube-system_fluentd-es-4eb5e468aec589f4a9ca8ce7d1e907cd43311b2aefecf0c02ff5318f9b0f9a6e.log"
```

**Comment by vide** [comment]
I had the same error while running this plugin with fluentd 0.12.40 in a local kubernetes cluster, the conf that did it for me was:
```
<match kubernetes.**>
       @type detect_exceptions
       message log
       remove_tag_prefix kubernetes
       multiline_flush_interval 1
</match>
```
basically removing the tag that I explicitly match (seems obvious written this way but I got it wrong the first time :P)

**Comment by vide** [comment]
@thomasjungblut Yes, that's it, that solved it for me. 

```
<source>
      type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      # we add this tag because the multiline plugin forces us to remove some tag after processing
      tag removeme.kubernetes.*
      read_from_head false
      format multi_format
      <pattern>
        format json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </pattern>
      <pattern>
        format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </pattern>
 </source>
```

plus the `<match>` snippet I've already posted

**Comment by thomasjungblut** [comment]
Thanks. That solves the deadlocking issue. @igorpeshansky any chance that this will be fixed? That's a terrible workaround, I had to go through tons of sources, filters and matches to add that prefix.

**Comment by ediphy-azorab** [comment]
a fairly straightforward way to handle this is to use the `@label` parameter that fluentd adds to the output plugin and do something along these lines...

```
<source>
  @type  forward
  @id    input1
  port  24224
  @label @RAW
</source>

<label @RAW>
  <match **>
    @type detect_exceptions
    multiline_flush_interval 0.5
    @label @COOKED
  </match>
</label>

<label @cooked>
  ...handle processed entries here...
</label>
```
