### ISSUE TITLE
Plugin error running against fluentd docker image v1.0

### ISSUE THREAD

**Issue by euangreen** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#31]
HI,

I'm trying to get the plugin working, using fluent/fluentd:v1.0-debian-onbuild base docker image. I'm not sure if this is an issue, config misconfiguration or version incompatibility

I've got the following in my Dockerfile to install the plugin:

```
FROM fluent/fluentd:v1.0-debian-onbuild
# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo gem install \
        fluent-plugin-elasticsearch \
        fluent-plugin-rewrite-tag-filter \
        fluent-plugin-concat \
        fluent-plugin-detect-exceptions \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem
```

Building the image, it looks like the plugin is installed:

```
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Successfully installed excon-0.60.0
Successfully installed multi_json-1.13.1
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.14.0
Successfully installed elasticsearch-transport-6.0.1
Successfully installed elasticsearch-api-6.0.1
Successfully installed elasticsearch-6.0.1
Successfully installed fluent-plugin-elasticsearch-2.8.1
Successfully installed fluent-plugin-rewrite-tag-filter-2.0.2
Successfully installed fluent-plugin-concat-2.2.0
Successfully installed fluent-plugin-detect-exceptions-0.0.9
11 gems installed
```

I've got the following fluentd config:

```
<match **>
  @type detect_exceptions
  remove_tag_prefix stdout
  message log
  languages java
  multiline_flush_interval 0.1
</match>
```

I'm getting the following error when starting the fluentd docker image:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /var/lib/gems/2.3.0/gems/fluent-plugin-detect-exceptions-0.0.9/lib/fluent/plugin/out_detect_exceptions (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/registry.rb:102:in `block in search'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/registry.rb:99:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/registry.rb:99:in `search'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/registry.rb:44:in `lookup'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:146:in `new_impl'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:104:in `new_output'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:128:in `add_match'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:72:in `block in configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:64:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:64:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:112:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:131:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:96:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:770:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:553:in `dry_run'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:571:in `supervise'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:476:in `run_supervisor'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
        from /usr/local/bin/fluentd:22:in `load'
        from /usr/local/bin/fluentd:22:in `<main>'
```

Should this be working or am I missing something?

**Comment by igorpeshansky** [comment]
We have not tested this plugin against fluentd v1.0 -- it's quite possible that something's broken. Can you try with v0.14 instead?

**Comment by euangreen** [comment]
HI, what is the latest version of v0.14 it has been tested against? I'm now trying  to  run against v0.14.15

**Comment by igorpeshansky** [comment]
We've been running version v0.0.8 with v0.14.25. The only thing that's changed in v0.0.9 is that the version pin was removed in the dependencies.

We generally don't recommend installing these gems individually -- our environment is all encapsulated in the [`google-fluentd` package](https://github.com/GoogleCloudPlatform/google-fluentd). You can install the package using the [public instructions](https://cloud.google.com/logging/docs/agent/installation). This plugin was designed to work with Google Cloud logging.

**Comment by euangreen** [comment]
OK, I was trying to find a way of detecting multiline logs and your plugin looked like it would be useful. We aren't using Google Cloud logging however, just docker containers with java services. so sounds like  a case of square peg round hole.

**Comment by igorpeshansky** [comment]
Ah. Have you seen the [multiline parser plugin](https://docs.fluentd.org/articles/parser_multiline)? They also have an example [specifically for Java stacktraces](https://docs.fluentd.org/articles/parser_multiline#java-stacktrace-log).

**Comment by euangreen** [comment]
Yes, looking into that now. Thanks for the quick responses.

**Comment by dsouzajude** [comment]
I liked this plugin a lot and started to investigate this issue myself since i want to use it too.

It seems when you install this plugin via the gem, it doesn't give `read` access to the files `exception_detector.rb` and `out_detect_exceptions.rb`.

```
-rw-r----- 1 root root 9.3K Mar 28 13:38 exception_detector.rb
-rw-r----- 1 root root 4.4K Mar 28 13:38 out_detect_exceptions.rb
```

After giving read access, for example, in my case i'm using [td-agent v3](https://docs.fluentd.org/v1.0/articles/install-by-deb) that uses `fluentd v1.0` in it's core, it installs the plugin at the location `/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.9/lib/fluent/plugin`.

Giving read access like the following resolved the issue and fluentd was able to startup successfully!

```
chmod oug+r /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.9/lib/fluent/plugin/*.rb
```

Now it should look something like:

```
-rw-r--r-- 1 root root 9.3K Mar 28 13:38 exception_detector.rb
-rw-r--r-- 1 root root 4.4K Mar 28 13:38 out_detect_exceptions.rb
```

Hope this helps.

**Comment by igorpeshansky** [comment]
Then it seems to be a duplicate of #32.
