### ISSUE TITLE
"deadlock; recursive locking"

### ISSUE THREAD

**Issue by addozhang** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#40]
Encounter error when POST log below

```
{
  "log": "2018-07-09 14:30:52.801 -ERROR 1 --- [http-nio-8899-exec-10] .x.l.n.c.c.GlobalDefaultExceptionHandler : Request method 'PUT' not supported",
  "stream": "stdout",
  "time": "2018-07-06T02:57:18.099261557Z"
}
```

```
/ # gem list

*** LOCAL GEMS ***

cool.io (1.5.3)
fluent-plugin-detect-exceptions (0.0.11)
fluentd (0.12.42)
http_parser.rb (0.6.0)
json (2.1.0)
msgpack (1.2.4)
oj (2.18.3)
openssl (default: 2.0.7)
psych (default: 2.2.2)
sigdump (0.2.4)
string-scrub (0.0.5)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2018.4)
yajl-ruby (1.3.1)
```

```
<source>
  @type http
  port 9880
  bind 0.0.0.0
</source>
<match **>
  @type detect_exceptions
  #remove_tag_prefix foo
  message log
  languages java
  multiline_flush_interval 0.1
</match>
<match **>
  @type stdout
</match>
```

```log
fluentd    | 2018-07-09 06:44:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'" tag="sample.test"
fluentd    |   2018-07-09 06:44:47 +0000 [warn]: suppressed same stacktrace
fluentd    | 2018-07-09 06:44:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'" tag="sample.test"
fluentd    |   2018-07-09 06:44:47 +0000 [warn]: suppressed same stacktrace
fluentd    | 2018-07-09 06:44:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'" tag="fluent.warn"
fluentd    |   2018-07-09 06:44:47 +0000 [warn]: suppressed same stacktrace
fluentd    | 2018-07-09 06:44:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'" tag="fluent.warn"
fluentd    |   2018-07-09 06:44:47 +0000 [warn]: suppressed same stacktrace
fluentd    | 2018-07-09 06:44:47 +0000 [error]: failed to emit fluentd's log event tag="fluent.warn" event={"error_class"=>"ThreadError", "error"=>"deadlock; recursive locking", "location"=>"/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'", "tag"=>"sample.test", "message"=>"emit transaction failed: error_class=ThreadError error=\"deadlock; recursive locking\" location=\"/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'\" tag=\"sample.test\""} error_class=ThreadError error=#<ThreadError: deadlock; recursive locking>
fluentd    | 2018-07-09 06:44:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'" tag="fluent.warn"
fluentd    |   2018-07-09 06:44:47 +0000 [warn]: suppressed same stacktrace
fluentd    | 2018-07-09 06:44:47 +0000 [warn]: emit transaction failed: error_class=ThreadError error="deadlock; recursive locking" location="/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'" tag="fluent.warn"
fluentd    |   2018-07-09 06:44:47 +0000 [warn]: suppressed same stacktrace
fluentd    | 2018-07-09 06:44:47 +0000 [error]: failed to emit fluentd's log event tag="fluent.warn" event={"error_class"=>"ThreadError", "error"=>"deadlock; recursive locking", "location"=>"/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'", "tag"=>"sample.test", "message"=>"emit transaction failed: error_class=ThreadError error=\"deadlock; recursive locking\" location=\"/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-detect-exceptions-0.0.11/lib/fluent/plugin/out_detect_exceptions.rb:131:in `synchronize'\" tag=\"sample.test\""} error_class=ThreadError error=#<ThreadError: deadlock; recursive locking>
```

**Comment by addozhang** [comment]
sorry, duplicated. #9
