### ISSUE TITLE
Nodejs & Express Stacktrace

### ISSUE THREAD

**Issue by azman0101** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#44]
I've this kind of trace when enable deep-monitoring which is equivalent to `–v8 –event-loop-inspector –trace`

```
CMD [ "pm2-runtime", "start", "pm2.json", "--deep-monitoring" ]
```

```
API error { Error: Request failed with status code 404
    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at IncomingMessage.emitted (/usr/local/lib/node_modules/pm2/node_modules/emitter-listener/listener.js:134:21)
    at endReadableNT (_stream_readable.js:1064:12)
    at /usr/local/lib/node_modules/pm2/node_modules/async-listener/glue.js:188:31
    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:219:9)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.16.2' },
     method: 'get',
     url: 'https://api-stage.domain.tld/api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49',
     data: undefined },
  request: 
   ClientRequest {
     domain: null,
     _events: 
      { socket: [Object],
        error: [Array],
        abort: [Object],
        aborted: [Object],
        timeout: [Object],
        prefinish: [Object],
        response: undefined },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api-stage.domain.tld',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api-stage.domain.tld',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 263,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 294726,
        [Symbol(bytesRead)]: 0 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api-stage.domain.tld',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'api-stage.domain.tld',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 263,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 294726,
        [Symbol(bytesRead)]: 0 },
     _header: 'GET /api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nx-cloud-trace-context: 45ca099c48e64025b9f320ffd2d28042/11705;o=1\r\nHost: api-stage.domain.tld\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49',
     _ended: true,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://api-stage.domain.tld/api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49',
        redirects: [],
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     onSocket: [Function],
     _redirectable: 
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://api-stage.domain.tld/api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49' },
     [Symbol(outHeadersKey)]: 
      { accept: [Array],
        'user-agent': [Array],
        'x-cloud-trace-context': [Array],
        host: [Array] } },
  response: 
   { status: 404,
     statusText: 'Not Found',
     headers: 
      { server: 'nginx',
        date: 'Wed, 26 Sep 2018 08:35:09 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '34',
        connection: 'close',
        'x-max-grace': '600s',
        'access-control-allow-origin': '*',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'PUT, GET, POST, DELETE, OPTIONS',
        'access-control-allow-headers': 'X-Requested-With, Origin, X-Csrftoken, Content-Type, Accept, Authorization',
        'x-varnish-ttl': '60.000',
        'x-backend': 'bo',
        'x-rvp-host': 'www-v2preprod-rvp1.domain.tld',
        'x-rvp-id': 'rvp1',
        age: '0',
        'x-cache': 'MISS (uncached)',
        'x-cache-age': '0' },
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: 'https://api-stage.domain.tld/api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49',
        data: undefined },
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nx-cloud-trace-context: 45ca099c48e64025b9f320ffd2d28042/11705;o=1\r\nHost: api-stage.domain.tld\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/v1/sections/stats.json?__uncache=2018-9-24%2016%3A04%3A49',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        onSocket: [Function],
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: { code: 404, message: 'Not Found' } } }
::ffff:10.52.47.4 - - [26/Sep/2018:08:35:10 +0000] "GET /stats.json?__uncache=2018-9-24%2016%3A04%3A49 HTTP/1.1" 404 - "https://review-feat-serve-tibdsa.ingress.staging.gcp.domain.tld/assets/sw.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36"
```

How could I handle this trace ?

**Comment by jpgonzalez1985** [comment]
hello my friend, try something like this:

https://github.com/jpgonzalez1985/fluent-plugin-detect-exceptions/commit/01da9c8e145b469985bd76bd38402217052a73dc

**Comment by thomasjungblut** [comment]
hey guys, can this be included and released properly? we're having the same issue :)

**Comment by igorpeshansky** [comment]
@jpgonzalez1985, care to submit a PR?
