### ISSUE TITLE
detect exceptions not handling java stack trace exceptions

### ISSUE THREAD

**Issue by lp060** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#51]
Hi,
I am running fluentd daemonset on a kubernetes cluster and redirecting logs to splunk. The following given stack trace is not seen at splunk after using the detect exception plugin also.

I have a stack trace like below:
```
2019-02-06 09:32:51.839 [qtp396180261-19 - /resteasy/exception] INFO  com.intuit.application.SyncControllerImpl - Stack trace of current thread using dumpStack() method
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.intuit.application.SyncControllerImpl.createException(SyncControllerImpl.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269)
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227)
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.createModelAndView(ResteasyHandlerAdapter.java:87)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:74)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:24)
	at org.jboss.resteasy.springmvc.ResteasyWebHandlerTemplate.handle(ResteasyWebHandlerTemplate.java:39)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:45)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:427)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:366)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:973)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1035)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:641)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
displaying Stack trace from StackTraceElement in Java
```
===================
This is my fluentd config:
```
<source>
      @type tail
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      read_from_head true

      path /var/log/containers/*.log
      pos_file /var/log/fluentd/es-containers.log.pos
      tag raw.kubernetes.*
    </source>

 # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message message
      stream stream
      languages java, python
      multiline_flush_interval 5
    </match>
    # Concatenate multi-line logs
    <filter kubernetes.**>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>
```
===============
I see only first and last line but not the actual stack trace
java.lang.Exception: Stack trace - this is seen
displaying Stack trace from StackTraceElement in Java - this is seen
the in between stack trace is lost

**Comment by igorpeshansky** [comment]
This plugin was designed to work with [Stackdriver logging](http://cloud.google.com/logging/) and [Stackdriver error reporting](https://cloud.google.com/error-reporting/). Do you observe the same issue with those tools?
Do you see the same issue when you remove the `concat` plugin and use [`out_stdout`](https://docs.fluentd.org/articles/out_stdout)?

**Comment by a-hat** [comment]
I have a similar issue, but my stacktrace seems to be untouched, each line of the stacktrace is forwarded in a separate log entry. Any help would be appreciated.

```
2019-06-14 09:15:36.930 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: No enum constant com.xxx.contract.EnvironmentType.LIVE2
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.xxx.contract.EnvironmentType.valueOf(EnvironmentType.java:3)
	at com.xxx.commons.boot.context.EnvironmentTypeProfileInitializer.onApplicationEvent(EnvironmentTypeProfileInitializer.java:20)
	at com.xxx.commons.boot.context.EnvironmentTypeProfileInitializer.onApplicationEvent(EnvironmentTypeProfileInitializer.java:13)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at de.xxx.grc.masterdata.MasterdataApplication.main(MasterdataApplication.java:43)
```

here is my fluentd config. The output is further forwarded to elasticsearch.

```
    <label @RAW>
      <match **>
        @type detect_exceptions
        message log
        multiline_flush_interval 0.1

        @label @OUTPUT
      </match>
    </label>
```

**Comment by Charith32** [comment]
You can resolve the issue by using muktiline command in source section and then using single value formatter inside the match section. Do you want to elaborate on this?

**Comment by savealive** [comment]
I have the same issue as @a-hat has. 
```
2019-07-20 20:58:11.287  WARN 1 --- [config-reloader] i.s.config.vault.VaultConfigSource       : unable to load config properties

com.bettercloud.vault.VaultException: Vault responded with HTTP status code: 403
Response body: {"errors":["permission denied"]}

	at com.bettercloud.vault.api.Logical.read(Logical.java:70) ~[vault-java-driver-3.1.0.jar:na]
	at com.bettercloud.vault.api.Logical.read(Logical.java:50) ~[vault-java-driver-3.1.0.jar:na]
	at io.scalecube.config.vault.VaultConfigSource.loadConfig(VaultConfigSource.java:58) ~[config-vault-0.3.6.jar:na]
	at io.scalecube.config.ConfigRegistryImpl.loadAndNotify(ConfigRegistryImpl.java:384) [config-0.3.6.jar:na]
	at io.scalecube.config.ConfigRegistryImpl.lambda$init$3(ConfigRegistryImpl.java:95) [config-0.3.6.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
```
Logs like this are not handled properly

**Comment by jkohen** [comment]
As @igorpeshansky explained, this plugin is intended to be used with Stackdriver. We can't provide help to set up Splunk.
